name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: wget https://github.com/rpgtex/DND-5e-LaTeX-Template/archive/master.zip
      - run: unzip -d "$(kpsewhich -var-value TEXMFHOME)/tex/latex/" master.zip
      - run: cd "$(kpsewhich -var-value TEXMFHOME)/tex/latex/"
      - run: mv DND-5e-LaTeX-Template-master dnd
      - name: Compile LaTeX FIles
        uses: dante-ev/latex-action@2024-B
        with:
          root_file: Session10.tex
          working_directory: sessions/S10
          compiler: pdflatex
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
