name: DND Github Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      SESSION: "10"
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "$SESSION"
      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  LaTeX-Build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v6
          
        - name: Download and Unzip DnD Template
          run: | 
            curl -OL https://github.com/rpgtex/DND-5e-LaTeX-Template/archive/master.zip
            unzip master.zip

        - name: Set Environment Variable
          run: echo "SESSION=10" >> $GITHUB_ENV
          run: echo "$SESSION"
        
        - name: Edit Main for Session Build
          run: |
            sed -i "s|\input{Last_Adventure}|\input{summary/S$SESSION_recap}|g" main.tex
            sed -i "s|\input{Adventure_Log}|\input{adv_log/S$SESSION_Adventure_Log}|g" main.tex
            sed -i "s|\part\*{Latest_Session}|\part\*{Session $SESSION}|g" main.tex



        - name: Generate PDF document
          uses: xu-cheng/latex-action@v3
          with: 
            root_file: main.tex
          env:
            TEXINPUTS: ".:./DND-5e-LaTeX-Template-stable//:"
            
        - name: Create Artifact
          uses: actions/upload-artifact@v7
          with:
            name: Latest
            path: main.pdf

            
            
        
  
          

