name: DND Github Action
run-name: Merge Request ${{ github.actor }}
on: 
  [push]
jobs:
  Sanity-Check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Current Job = ${{ github.job }}"
          echo "Repo Owner = ${{ github.repository_owner }}"
          echo "GitHub Event = ${{ github.event_name }}"
          echo "OS = ${{ runner.os }} server hosted by GitHub!"
          echo "Repository = ${{ github.repository }}"
          echo "Branch Name = ${{ github.ref }}"
          echo "Reference Name = ${{ github.ref_name }}"
          echo "Actor = ${{ github.actor }}"

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: env > environment.txt

      - name: Create Environment Artifact
        uses: actions/upload-artifact@v7
        with:
          name: environment
          path: environment.txt


  Latest-Update:
      runs-on: ubuntu-latest
      outputs:
        l_summary: ${{ steps.get_latest_variables.outputs.LATEST_SUMMARY }}
        l_log: ${{ steps.get_latest_variables.outputs.LATEST_LOG }}
        l_session: ${{ steps.get_latest_variables.outputs.SESSION_NUMBER }}

        
      steps:
        - name: Checkout Repository
          run: |
              LATEST_SUMMARY=$( ls -1r summary/ | head -n1 )
              LATEST_ADV_LOG=$( ls -1r adv_log/ | head -n1 )
              SESSION_NUMBER=$( ls -1r sessions/ | head -n1 | sed 's/[^0-9]//g' )

        - name: Get Variables
          id: latest_variables
          run: |
            echo "LATEST_SUMMARY=${LATEST_SUMMARY}" >> "$GITHUB_OUTPUT"
            echo "LATEST_LOG=${LATEST_ADV_LOG}" >> "$GITHUB_OUTPUT"
            echo "SESSION_NUMBER=${SESSION_NUMBER}" >> "$GITHUB_OUTPUT"



  LaTeX-Build:
      runs-on: ubuntu-latest
      needs:
        Latest-Update
      steps:
        - name: Current Job
          run: echo  "${{ github.job }}"
        
        - name: Check out repository
          uses: actions/checkout@v6
          
        - name: Download and Unzip DnD Template
          run: | 
            curl -OL https://github.com/rpgtex/DND-5e-LaTeX-Template/archive/master.zip
            unzip master.zip

        - name: Set Environment Variable
          run: echo "SESSION=11" >> $GITHUB_ENV
        - run: echo "'$SESSION'"
        
        - name: Edit Main for Session Build
          run: |
            sed -i "s|\input{Last_Adventure}|\input{summary/${{ needs.Latest-Update.outputs.l_summary }}}|g" main.tex
            sed -i "s|\input{Adventure_Log}|\input{adv_log/${{ needs.Latest-Update.outputs.l_log }}}|g" main.tex
            sed -i "s|\part\*{Latest_Session}|\part\*{Session ${{ needs.Latest-Update.outputs.l_session }}}|g" main.tex



        - name: Generate PDF document
          uses: xu-cheng/latex-action@v3
          with: 
            root_file: main.tex
          env:
            TEXINPUTS: ".:./DND-5e-LaTeX-Template-stable//:"
            
        - name: Create Artifact
          uses: actions/upload-artifact@v7
          with:
            name: Session_${{env.SESSION}}
            path: main.pdf

            
            
        
  
          

