name: DND Github Action
run-name: Merge Request ${{ github.actor }}
on: 
  [push]
jobs:
  Sanity-Check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Current Job = ${{ github.job }}"
      - run: echo "Repo Owner = ${{ github.repository.owner }}"
      - run: echo "GitHub Event = ${{ github.event_name }}"
      - run: echo "OS = ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Repository = ${{ github.repository }}"
      - run: echo "Branch Name = ${{ github.ref }}"
      - run: echo "Reference Name = ${{ github.ref_name }}"
      - run: echo "Actor = ${{ github.actor }}"

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: env > environment.txt

      - name: Create Environment Artifact
        uses: actions/upload-artifact@v7
        with:
          name: environment
          path: environment.txt

  LaTeX-Build:
      runs-on: ubuntu-latest
      steps:
        - name: Current Job
          run: echo  "${{ github.job }}"
        
        - name: Check out repository
          uses: actions/checkout@v6
          
        - name: Download and Unzip DnD Template
          run: | 
            curl -OL https://github.com/rpgtex/DND-5e-LaTeX-Template/archive/master.zip
            unzip master.zip

        - name: Set Environment Variable
          run: echo "SESSION=11" >> $GITHUB_ENV
        - run: echo "'$SESSION'"
        
        - name: Edit Main for Session Build
          run: |
            sed -i "s|\input{Last_Adventure}|\input{summary/S"$SESSION"_recap}|g" main.tex
            sed -i "s|\input{Adventure_Log}|\input{adv_log/S"$SESSION"_Adventure_Log}|g" main.tex
            sed -i "s|\part\*{Latest_Session}|\part\*{Session "$SESSION"}|g" main.tex



        - name: Generate PDF document
          uses: xu-cheng/latex-action@v3
          with: 
            root_file: main.tex
          env:
            TEXINPUTS: ".:./DND-5e-LaTeX-Template-stable//:"
            
        - name: Create Artifact
          uses: actions/upload-artifact@v7
          with:
            name: Session_${{env.SESSION}}
            path: main.pdf

            
            
        
  
          

